
PRODUCT_URLS = [
    'https://audac.eu/eu/products/d/ateo2s---ateo2-with-surface-ceiling-mount',
    'https://audac.eu/eu/products/d/ateo2---compact-wall-speaker-with-clevermount-2inch',
    'https://audac.eu/eu/products/d/ateo4---wall-speaker-with-clevermount-4inch',
    'https://audac.eu/eu/products/d/ateo4m---in--outdoor-surface-mount-loudspeaker-with-clevermountplus',
    'https://audac.eu/eu/products/d/ateo6---wall-speaker-with-clevermount-6inch',
    'https://audac.eu/eu/products/d/ateo6m---in--outdoor-surface-mount-loudspeaker-with-clevermountplus',
    'https://audac.eu/eu/products/d/alti4---2-way-4inch-pendant-speaker',
    'https://audac.eu/eu/products/d/alti4m---2-way-4inch-design-surface-mount-loudspeakers',
    'https://audac.eu/eu/products/d/alti6---2-way-6inch-pendant-speaker',
    'https://audac.eu/eu/products/d/alti6m---2-way-6-5inch-design-surface-mount-loudspeakers',
    'https://audac.eu/eu/products/d/wx302_o---outdoor-universal-wall-speaker-3inch',
    'https://audac.eu/eu/products/d/wx502_o---outdoor-universal-wall-speaker-5-1-4inch',
    'https://audac.eu/eu/products/d/wx802_o---outdoor-universal-wall-speaker-8inch',
    'https://audac.eu/eu/products/d/xeno6---full-range-speaker-6inch',
    'https://audac.eu/eu/products/d/xeno8---full-range-speaker-8inch',
    'https://audac.eu/eu/products/d/vexo8---compact-high-power-speaker-8inch',
    'https://audac.eu/eu/products/d/vexo108---8inch-high-performance-2-way-loudspeaker',
    'https://audac.eu/eu/products/d/vexo110---10inch-high-performance-2-way-loudspeaker',
    'https://audac.eu/eu/products/d/vexo112---12inch-high-performance-2-way-loudspeaker',
    'https://audac.eu/eu/products/d/vexo115---15inch-high-performance-2-way-loudspeaker',
    'https://audac.eu/eu/products/d/fx1-18---high-output-bass-cabinet-18inch',
    'https://audac.eu/eu/products/d/fx3-15---high-output-cabinet-15inch',
    'https://audac.eu/eu/products/d/celo2---high-end-ceiling-speaker-2inch',
    'https://audac.eu/eu/products/d/celo5---high-end-2-way-5inch-ceiling-speaker',
    'https://audac.eu/eu/products/d/celo6---high-end-2-way-6inch-ceiling-speaker',
    'https://audac.eu/eu/products/d/celo8---high-end-2-way-8inch-ceiling-speaker',
    'https://audac.eu/eu/products/d/celo8s---high-end-8inch-ceiling-subwoofer',
    'https://audac.eu/eu/products/d/mero2---high-end-in-wall-speaker-2inch',
    'https://audac.eu/eu/products/d/mero5---high-end-2-way-in-wall-speaker-5inch',
    'https://audac.eu/eu/products/d/mero6---high-end-2-way-in-wall-speaker-6inch',
    'https://audac.eu/eu/products/d/cali424---safelatch-2-way-4inch-ceiling-speaker-with-twist-fix-grill',
    'https://audac.eu/eu/products/d/cali660---safelatch-2-way-6-5inch-ceiling-speaker-with-twist-fix-grill',
    'https://audac.eu/eu/products/d/cira5---quickfit-2-way-5-1-4inch-ceiling-speaker-with-twistfix-grill',
    'https://audac.eu/eu/products/d/cira7---quickfit-2-way-6-5inch-ceiling-speaker-with-twistfix-grill',
    'https://audac.eu/eu/products/d/cira8---quickfit-2-way-8inch-ceiling-speaker-with-twistfix-grill',
    'https://audac.eu/eu/products/d/cena3---springfit-2-5inch-ceiling-speaker',
    'https://audac.eu/eu/products/d/cena5---springfit-5inch-ceiling-speaker',
    'https://audac.eu/eu/products/d/cena7---springfit-6-5inch-ceiling-speaker',
    'https://audac.eu/eu/products/d/cena8---springfit-8inch-ceiling-speaker',
    'https://audac.eu/eu/products/d/baso10---compact-10inch-bass-reflex-cabinet',
    'https://audac.eu/eu/products/d/baso12---compact-12inch-bass-reflex-cabinet',
    'https://audac.eu/eu/products/d/baso15---compact-15inch-bass-reflex-cabinet',
    'https://audac.eu/eu/products/d/baso18---compact-18inch-bass-reflex-cabinet',
    'https://audac.eu/eu/products/d/vexo110---10inch-high-performance-2-way-loudspeaker',
    'https://audac.eu/eu/products/d/vexo112a---12inch-high-performance-2-way-active-loudspeaker',
    'https://audac.eu/eu/products/d/vexo115a---15inch-high-performance-2-way-active-loudspeaker',
    'https://audac.eu/eu/products/d/noba8',
    'https://audac.eu/eu/products/d/noba8a',
    'https://audac.eu/eu/products/d/kyra6---design-column-speaker-6-x-2inch',
    'https://audac.eu/eu/products/d/kyra12---design-column-speaker-12-x-2inch',
    'https://audac.eu/eu/products/d/kyra12_o---outdoor-design-column-speaker-12-x-2inch',
    'https://audac.eu/eu/products/d/kyra24---design-column-speaker-24-x-2inch',
    'https://audac.eu/eu/products/d/lino4---column-speaker-4-x-2inch',
    'https://audac.eu/eu/products/d/lino10---column-speaker-10-x-2inch',
    'https://audac.eu/eu/products/d/cha530---2-way-horn-loudspeaker-5inch',
    'https://audac.eu/eu/products/d/cha660---2-way-horn-loudspeaker-6-5inch',
    'https://audac.eu/eu/products/d/hs208---full-range-horn-speaker-8inch',
    'https://audac.eu/eu/products/d/hs208t---full-range-horn-speaker-8inch-100v',
    'https://audac.eu/eu/products/d/hs212---full-range-horn-speaker-12inch',
    'https://audac.eu/eu/products/d/hs212t---full-range-horn-speaker-12inch-100v',
    'https://audac.eu/eu/products/d/sp20---sound-projector',
    'https://audac.eu/eu/products/d/sp202---heavy-duty-bidirectional-sound-projector',
    'https://audac.eu/eu/products/d/sp22---heavy-duty-sound-projector',
    'https://audac.eu/eu/products/d/wx302---universal-wall-speaker-3inch',
    'https://audac.eu/eu/products/d/wx502---universal-wall-speaker-5-1-4inch',
    'https://audac.eu/eu/products/d/wx802---universal-wall-speaker-8inch',
    'https://audac.eu/eu/products/d/viro5',
]


keyword_dictionary = {
    'Тип АС' : ['Speaker type'],
    'Широкополосная' : ['Full range'],
    'Пиковая мощность' : ['Peak power handling'],
    'Продолжительная мощность' : ['RMS/AES power handling'],
    'Отклик (± 3 дБ)' : ['Response (± 3 dB)'],
    '208 Ω - 100 В / Нет - 70 В / 24 Вт' : ['208 Ω - 100 V / Not used - 70 V / 24 W'],
}