
replace_words = {
    'Speaker type' : 'Тип АС',
    'Full range' : 'Широкополосная',
    'Peak power handling' : 'Пиковая мощность',
    'RMS/AES power handling' : 'Продолжительная мощность',
    'Impedance' : 'Сопротивление',
    'Incline angle' : 'Угол наклона',
    'Left' : 'Влево',
    'Right' : 'Вправо',
    'Bottom' : 'Вниз',
    'Top' : 'Вверх',
    'Sensitivity (1W/1m)' : 'Чувыствительность (1Вт/1м)',
    'W' : 'Вт',
    'dB' : 'дБ',
    'Sound Pressure (Max. W/1m)' : 'Звуковое давление (Макс. Вт/1м)',
    'V' : 'В',
    'Frequency' : 'Частота',
    'Response (± 3 dB)' : 'Отклик (± 3 дБ)',
    'Range (-10 dB)' : 'Диапозон (-10 дБ)',
    'Dispersion' : 'Угол раскрытия',
    'Horizontal' : 'Горизонтальный',
    'Vertical' : 'Вертикальный',
    'Connectors' : 'Подключение',
    '6-pin Custom Terminal Block' : '6-пин клеммный блок',
    'Drivers' : 'Драйверы',
    '1” Dome tweeter' : '1” Купольный',
    '4” MF / LF Woofer' : '4” СЧ / НЧ',
    'Line Transformer Tappings' : 'Режимы трансформатора',
    '208 Ω - 100 V / Not used - 70 V / 24 W' : '208 Ω - 100 В / Нет - 70 В / 24 Вт',
    '417 Ω - 100 V / 24 W - 70 V / 12 W' : '417 Ω - 100 В / 24 Вт - 70 В / 12 Вт',
    '833 Ω - 100 V / 12 W - 70 V / 6 W' : '833 Ω - 100 В / 12 Вт - 70 В / 6 Вт',
    '1667 Ω - 100 V / 6 W - 70 V / 3 W' : '1667 Ω - 100 В / 6 Вт - 70 В / 3 Вт',
    'Dimensions' : 'Размеры',
    '136 x 244 x 153 mm (W x H x D)' : '136 x 244 x 153 мм (Ш x В x Г)',
    'Weight' : 'Вес',
    'Operating temperature' : 'Температурный диапозон',
    'Mounting' : 'Крепление',
    'Accessories' : 'Аксессуары',
    'Included' : 'В комплекте',
    'Construction' : 'Конструкция',
    'Front finish' : 'Лицевая отделка',
    'Steel grill' : 'Стальной грилль',
    'Colours' : 'Рассцветка',
    'Black (RAL9005) (ATEO4/B, ATEO4D/B)' : 'Черный (RAL9005) (ATEO4/B, ATEO4D/B)',
    'White (RAL9003) (ATEO4/W, ATEO4D/W)' : 'Белый (RAL9003) (ATEO4/W, ATEO4D/W)',
}


keyword_dictionary = {
    'Тип АС' : ['Speaker type'],
    'Широкополосная' : ['Full range'],
    'Пиковая мощность' : ['Peak power handling'],
    '40 Вт' : ['40 W'],
    'Программируемая мощность' : ['Program power handling'],
    '20 Вт' : ['20 W'],
    'Продолжительная мощность' : ['RMS/AES power handling'],
    '10 Вт' : ['10 W'],
    'Сопротивление' : ['Impedance'],
    'Угол наклона' : ['Incline angle'],
    'Влево' : ['Left'],
    'Вправо' : ['Right'],
    'Вниз' : ['Bottom'],
    'Вверх' : ['Top'],
    'Чувыствительность (1Вт/1м)' : ['Sensitivity (1W/1m)'],
    '83 дБ' : ['83 dB'],
    'Звуковое давление (Макс. Вт/1м)' : ['Sound Pressure (Max. W/1m)'],
    '93 дБ' : ['93 dB'],
    'Частота' : ['Frequency'],
    'Отклик (± 3 дБ)' : ['Response (± 3 dB)'],
    '120 Гц - 20 кГц' : ['120 Hz - 20 kHz'],
    'Диапозон (-10 дБ)' : ['Range (-10 dB)'],
    '100 Гц - 20 кГц' : ['100 Hz - 20 kHz'],
    'Угол раскрытия' : ['Dispersion'],
    'Горизонтальный': ['Horizontal'],
    'Вертикальный' : ['Vertical'],
    'Драйверы' : ['Drivers'],
    '208 Ω - 100 В / Нет - 70 В / 24 Вт' : ['208 Ω - 100 V / Not used - 70 V / 24 W'],
}